/**
 * `COMMAND.md` — the run's recipe (§11 P8).
 *
 * The plan's exit criterion for the evidence set is that **every run is re-runnable from its own
 * directory**, which makes this file a small contract with two halves that fail in different ways:
 * a command that was reconstructed wrongly produces a run of a *different* shape (a sim dropped, an
 * input lost, a flag the caller never passed), and a command that is right but rendered without the
 * scrubber puts the caller's own values into a file next to the evidence (§6's sink list is
 * exhaustive by construction, and a hand-written sink is exactly what "by construction" forbids).
 *
 * The third thing asserted here is the one a reader of a *failed* run needs: that the file says the
 * non-zero exit is the result rather than a broken copy-paste. That is the difference between an
 * evidence directory someone can use and one they spend twenty minutes doubting.
 */
import { readFile } from "node:fs/promises";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { discoverCommandLine, parseArgs as parseDiscoverArgs } from "../../src/cli/discover.ts";
import { environmentOverrides, shellArg, writeCommandSheet } from "../../src/cli/io.ts";
import { parseArgs as parseReplayArgs, replayCommandLine } from "../../src/cli/replay.ts";
import { REDACTED, Redactor } from "../../src/policy/redact.ts";

const SSN = "412-88-9077";

function replayArgs(argv: readonly string[]) {
  const parsed = parseReplayArgs(argv);
  if (!parsed.ok) throw new Error(`expected these args to parse: ${parsed.problem}`);
  return parsed.args;
}

function discoverArgs(argv: readonly string[]) {
  const parsed = parseDiscoverArgs(argv);
  if (!parsed.ok) throw new Error(`expected these args to parse: ${parsed.problem}`);
  return parsed.args;
}

/** The shipped policy's `redact` section, which is what a run actually scrubs with. */
function redactor(): Redactor {
  return new Redactor({ fieldPatterns: ["password", "ssn", "account_number"] });
}

describe("quoting a value for the shell", () => {
  it("leaves a plain value alone, so the common command stays readable", () => {
    expect(shellArg("member-savings-balance")).toBe("member-savings-balance");
    expect(shellArg("http://localhost:4173/member/12345/summary")).toBe(
      "http://localhost:4173/member/12345/summary",
    );
  });

  it("quotes the characters a URL or a goal actually contains", () => {
    // `?` and `&` are the ones that silently truncate a sim-carrying `--entry` — the evidence runs
    // depend on exactly this flag, so a lost query string is a run of the wrong shape.
    expect(shellArg("http://localhost:4173/?sim=record-locked&x=1")).toBe(
      "'http://localhost:4173/?sim=record-locked&x=1'",
    );
    expect(shellArg("Look up member 12345")).toBe("'Look up member 12345'");
  });

  it("survives a value that contains a quote, rather than emitting a command that cannot run", () => {
    const hostile = "it's a balance";
    expect(shellArg(hostile)).toBe("'it'\\''s a balance'");
    // Spelled out: close the quote, escape one quote, reopen. A `sh` reading it gets the value back.
    expect(shellArg(hostile).replaceAll("'\\''", "'")).toBe(`'${hostile}'`);
  });
});

describe("the command a run is regenerated by", () => {
  it("spells a default replay without the flags that only repeat a default", () => {
    expect(replayCommandLine(replayArgs(["member-savings-balance", "--memberId", "12345"]))).toBe(
      "npm run replay -- member-savings-balance --memberId 12345",
    );
  });

  it("keeps every flag that changes what the run does, in the order it was given", () => {
    const line = replayCommandLine(
      replayArgs([
        "member-savings-balance",
        "--version",
        "2",
        "--memberId",
        "12345",
        "--entry",
        "http://localhost:4173/?sim=dialog=known",
        "--policy",
        "policy/shrunk.json",
        "--allow-drift",
        "--headed",
        "--json",
      ]),
    );
    expect(line).toBe(
      "npm run replay -- member-savings-balance --version 2 --memberId 12345 " +
        "--entry 'http://localhost:4173/?sim=dialog=known' --policy policy/shrunk.json " +
        "--allow-drift --headed --json",
    );
  });

  it("names the goal for discovery, and declares the inputs as the caller did", () => {
    const line = discoverCommandLine(
      discoverArgs([
        "--goal",
        "Look up member 12345 and read their current savings balance",
        "--param",
        "memberId=12345",
        "--id",
        "member-savings-balance",
      ]),
    );
    expect(line).toBe(
      "npm run discover -- --goal 'Look up member 12345 and read their current savings balance' " +
        "--param memberId=12345 --id member-savings-balance",
    );
  });

  it("treats a discovery goal as one shell word, quotes and all", () => {
    const line = discoverCommandLine(discoverArgs(["--goal", "Read the member's balance"]));
    expect(line).toContain("--goal 'Read the member'\\''s balance'");
  });
});

describe("the environment a recipe names", () => {
  it("names the knobs that are set, and nothing else", () => {
    expect(environmentOverrides({})).toEqual([]);
    expect(environmentOverrides({ PORT: "4173", OPENAI_MODEL: "some-model" })).toEqual([
      "In force for this command: `PORT=4173`, `OPENAI_MODEL=some-model`.",
    ]);
    // An empty variable is not an override: `.env` parsing and `export X=` both produce one.
    expect(environmentOverrides({ POLICY_PATH: "" })).toEqual([]);
  });
});

describe("the file itself", () => {
  it("carries the command, the outcome, the exit code and the notes", async () => {
    const runDir = await mkdtemp(join(tmpdir(), "command-sheet-"));
    await writeCommandSheet(redactor(), runDir, {
      what: "replay — member-savings-balance (latest)",
      command: "npm run replay -- member-savings-balance --memberId 12345",
      outcome: "success — savingsBalance: $4,201.55",
      exitCode: 0,
      notes: ["Drift preflight (§26) — match: the target advertises atlas-console/base@0.1, as recorded."],
    });

    const file = await readFile(join(runDir, "COMMAND.md"), "utf8");
    expect(file).toContain("# replay — member-savings-balance");
    expect(file).toContain("npm run replay -- member-savings-balance --memberId 12345");
    expect(file).toContain("success — savingsBalance: $4,201.55");
    expect(file).toContain("Exit code `0` — success or business outcome");
    expect(file).toContain("Drift preflight (§26) — match");
  });

  it("scrubs the command it writes, because a command quotes the caller's own inputs", async () => {
    const runDir = await mkdtemp(join(tmpdir(), "command-sheet-"));
    const scrubber = redactor();
    scrubber.noteValue(SSN);
    await writeCommandSheet(scrubber, runDir, {
      what: "replay — taxpayer-lookup (latest)",
      command: `npm run replay -- taxpayer-lookup --ssn ${SSN}`,
      outcome: "success",
      exitCode: 0,
    });

    const file = await readFile(join(runDir, "COMMAND.md"), "utf8");
    expect(file).not.toContain(SSN);
    expect(file).toContain(REDACTED);
  });

  it("says out loud that a failed run's exit code is its result, not a broken copy-paste", async () => {
    const runDir = await mkdtemp(join(tmpdir(), "command-sheet-"));
    await writeCommandSheet(redactor(), runDir, {
      what: "replay — member-savings-balance (latest)",
      command: "npm run replay -- member-savings-balance --memberId 12345 --entry 'http://localhost:4173/?sim=page-error'",
      outcome: "failure (replay): UNEXPECTED_STATE",
      exitCode: 1,
      notes: [
        "The exit code above is this run's result, not a broken reproduction: the command is right, and the state it was pointed at is what the result describes.",
      ],
    });

    const file = await readFile(join(runDir, "COMMAND.md"), "utf8");
    expect(file).toContain("Exit code `1` — run failure");
    expect(file).toContain("not a broken reproduction");
  });

  it("says so when the run used every default, rather than leaving an empty section", async () => {
    const runDir = await mkdtemp(join(tmpdir(), "command-sheet-"));
    await writeCommandSheet(redactor(), runDir, {
      what: "replay — member-savings-balance (latest)",
      command: "npm run replay -- member-savings-balance --memberId 12345",
      outcome: "success",
      exitCode: 0,
    });
    expect(await readFile(join(runDir, "COMMAND.md"), "utf8")).toContain(
      "Nothing beyond the command above: this run used every default.",
    );
  });
});
